apiVersion: v1
kind: Secret
metadata:
  name: {{ include "distribution.fullname" . }}-config
  labels:
    {{- include "distribution.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
    {{- include "distribution.config" . | nindent 4 }}
